/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import D20Glb from "./d20.glb?url";

type D20ModelProps = {
  color?: THREE.ColorRepresentation;
} & JSX.IntrinsicElements["group"];

type GLTFResult = GLTF & {
  nodes: {
    D20_1: THREE.Mesh;
    D20_2: THREE.Mesh;
  };
  materials: {
    D20Base: THREE.MeshStandardMaterial;
    D20Numbers: THREE.MeshStandardMaterial;
  };
};

export function D20Model({ color, ...rest }: D20ModelProps) {
  const { nodes, materials } = useGLTF(D20Glb) as GLTFResult;
  return (
    <group {...rest} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.D20_1.geometry}>
          <meshStandardMaterial color={color} roughness={0.175} />
        </mesh>
        <mesh geometry={nodes.D20_2.geometry} material={materials.D20Numbers} />
      </group>
    </group>
  );
}

useGLTF.preload(D20Glb);
